server:
    port: 8080
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:h2:~/cartbl
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2



management:
    endpoint:
         metrics:
              enabled: true
         prometheus:
              enabled: true
    endpoints:
        web:
           exposure:
               include: '*'

    metrics:
        export:
            prometheus:
                 enabled: true