server:
  port: 9995
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9991/eureka/
  spring:
    datasource:
       url: jdbc:h2:mem:testdb
       driverClassName: org.h2.Driver
       username: sa
       password: 12345
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  # Enabling H2 Console
    h2:
      console:
        enabled: true
  # Custom H2 Console URL
        path: /h2